theme: minima
title: Abhinav's Website
author: Abhinav Jha
email: abhijha512@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal website licensed under DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE.
  This site is hosted at Github Pages and created with Jekyll, Vim and vigour. 
  
# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: jha-abhinav # DO NOT include the @ character, or else the build will fail!
mastodon:
  - username: Abhinavjha
    instance: freeradical.zone

show_excerpts: false # set to false to remove excerpts on the homepage
markdown: CommonMarkGhPages
